### ISSUE TITLE
x509: certificate private key does not implement crypto.Signer 

### ISSUE THREAD

**Issue by amanjuneja5** [HewlettPackard/devid-provisioning-tool#7]
INFO[0000] Opening TPM device "/dev/tpmrm0"             
INFO[0000] Connecting to provisioning server "localhost:8443" 
INFO[0000] Preparing signing request                    
DEBU[0000] Creating CSR                                 
INFO[0000] Reading EK certificate from NV index 01c00002 
DEBU[0000] Parsing EK certificate                       
INFO[0000] Get Endorsement Key (RSA)                    
INFO[0000] Get Attestation Key (RSA)                    
INFO[0001] Get DevID (RSA)                              
INFO[0005] Certifying TPM-residency of keys             
INFO[0005] CSR creation complete! [3]                   
DEBU[0005] Marshaling CSR                               
DEBU[0005] Signing CSR                                  
DEBU[0005] Starting enroll stream                       
DEBU[0005] Sending signing request                      
DEBU[0005] Receiving challenge                          
DEBU[0005] Activating credential (a.k.a. solving challenge) 
DEBU[0006] Sending challenge response                   
DEBU[0006] Receiving signed certificates                
DEBU[0006] Flushing TPM resources                       
FATA[0006] Provisioning failed: enrollment process failed: receiving signed certificates failed: rpc error: code = Unknown desc = x509: certificate private key does not implement crypto.Signer

**Comment by yonas** [comment]
@amanjuneja5 How was this resolved?

**Comment by amanjuneja5** [comment]
@yonas -  Look at the comment on this one - https://github.com/HewlettPackard/devid-provisioning-tool/issues/6
That solves the issue.
